# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech Musings & Tips
email: me@zackarychapple.guru
description: > # this means to ignore newlines until "baseurl:"
  As I find things to write about I will post them here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zackarychapple.guru" # the base hostname & protocol for your site
twitter_username: zchapple
github_username:  zackarychapple

webproperty: UA-18164327-4
# Build settings
markdown: kramdown
